### ISSUE TITLE
OverflowError on 32-bit Python

### ISSUE THREAD

**Issue by prurph** [alexanderlukanin13/coolname#1]
Hi there! I tired using coolname with 32-bit Python (on Windows, both Python 2 and Python 3) and got an `OverflowError` from [this line](https://github.com/alexanderlukanin13/coolname/blob/master/coolname/impl.py#L151) originating from trying to [create the default generator](https://github.com/alexanderlukanin13/coolname/blob/master/coolname/impl.py#L584).

I assume that only 64-bit versions are supported, but just a heads up since the readme doesn't mention it explicitly. Thanks!

**Comment by alexanderlukanin13** [comment]
@prurph coolname 1.1.0 is released, now it must support any 32-bit Python version.
