### ISSUE TITLE
Feature request: custom words separator

### ISSUE THREAD

**Issue by khssnv** [alexanderlukanin13/coolname#11]
Currently, `coolname.generate_slug()` always uses `-` as a words separator. It would be nice to allow a user-defined separator.

## Example

```python
>>> import coolname
>>> coolname.generate_slug('_')
competent_earthworm_of_weird_pleasure
```

**Comment by alexanderlukanin13** [comment]
Alisher, thank you for your interest and for the idea, but I have to decline the PR according to "keep it simple" principle. It's trivial to write a custom function doing `'_'.join(generate())`. "slug" was intended in a narrow sense, like in Django, words-with-hyphens :-)
