### ISSUE TITLE
Add CLI functionality

### ISSUE THREAD

**Issue by matthewfeickert** [alexanderlukanin13/coolname#13]
:wave: Hi. Thanks for making `coolname`! It is one of my favorite tools for making human readable workflow slugs. A feature request would be to add command line functionality, so that you could have something like

```
$ coolname generate-slug -n 2  # accomplished-cheetah
```

which would basically be the same as calling

```
$ python -c 'from coolname import generate_slug; print(generate_slug(2))'
```

This would also be nice as then people could get it as a global CLI tool with [`pipx`](https://github.com/pypa/pipx). :sparkles:

**Comment by alexanderlukanin13** [comment]
Hi Matthew! Please try coolname 2.0.0, it should work in command line and support installation via pipx.
```
$ coolname
macho-burgundy-bittern-of-pizza
```
You can check additional options via `--help`.
