### ISSUE TITLE
Conda recipe?

### ISSUE THREAD

**Issue by vinisalazar** [alexanderlukanin13/coolname#6]
Hi,

thank you for providing this package. I'm finding it really useful.

Would you be willing to provide a conda distribution for it, through @conda-forge for example?

I could submit a draft recipe but would need a core developer to step up as maintainer.

Thank you,

V

**Comment by vinisalazar** [comment]
I hope this is OK, but I went forward and submitted a PR for this (conda-forge/staged-recipes#13541) listing myself as maintainer. However, it is always better if that role is done by the developers of the package, if that is possible.

Thank you,

V

**Comment by alexanderlukanin13** [comment]
Thank you for the conda recipe, I appreciate your help and I'm happy that someone actually uses this :-) I'll push an updated recipe with myself as a maintainer when I make the next version.
