### ISSUE TITLE
generate_slug generates deterministic names

### ISSUE THREAD

**Issue by muaali** [alexanderlukanin13/coolname#7]
Hi,
I am facing a very strange issue that is `coolname.generate_slug()` creates deterministic names inside python package. If I import the module in Python console and try out separately, everything works the way it is supposed to.
like
```
$ conda activate my_env
$ python
> from coolname import generate_slug
> generate_slug()
```
 Any ideas why this could be happening.

**Comment by muaali** [comment]
I think the problem might be I am using 
`random.seed(30)`
so it generates similar names in a sequence or so ?

**Comment by alexanderlukanin13** [comment]
Are you doing basically this?

```
>>> from random import seed
>>> from coolname import generate_slug
>>> seed(30)
>>> generate_slug()
'vagabond-kingfisher-of-inevitable-expression'
>>> generate_slug()
'imported-tactful-ape-of-happiness'
>>> seed(30)
>>> generate_slug()
'vagabond-kingfisher-of-inevitable-expression'
>>> generate_slug()
'imported-tactful-ape-of-happiness'
```

This is expected behavior: coolname uses standard Python pseudo-random number generator, and `seed(30)` initializes exactly the same sequence every time.

If you just want to use `generate_slug`, you don't need to call `seed`.

**Comment by muaali** [comment]
Hi. Yes exactly this is the issue I am facing. The seed was globally declared in a separate function (while it should have been locally) and it took me some time to debug it. But thanks, fixed now and works.
